INSERT INTO `categories` VALUES ('1', 'AUDI', null, null, null);
INSERT INTO `categories` VALUES ('2', 'BMW', null, null, null);
INSERT INTO `categories` VALUES ('3', 'CHEVROLET', null, null, null);
INSERT INTO `categories` VALUES ('4', 'CHRYSLER', null, null, null);
INSERT INTO `categories` VALUES ('5', 'CLARK', null, null, null);
INSERT INTO `categories` VALUES ('6', 'DAEWOO', null, null, null);
INSERT INTO `categories` VALUES ('7', 'DAIHATSU', null, null, null);
INSERT INTO `categories` VALUES ('8', 'DATSUN', null, null, null);
INSERT INTO `categories` VALUES ('9', 'DODGE', null, null, null);
INSERT INTO `categories` VALUES ('10', 'EVINRUDE', null, null, null);
INSERT INTO `categories` VALUES ('11', 'EZGO', null, null, null);
INSERT INTO `categories` VALUES ('12', 'FORD', null, null, null);
INSERT INTO `categories` VALUES ('13', 'FREIGHTLINER', null, null, null);
INSERT INTO `categories` VALUES ('14', 'GEO', null, null, null);
INSERT INTO `categories` VALUES ('15', 'GLASTRON', null, null, null);
INSERT INTO `categories` VALUES ('16', 'GOLF', null, null, null);
INSERT INTO `categories` VALUES ('17', 'HONDA', null, null, null);
INSERT INTO `categories` VALUES ('18', 'HYUNDAI', null, null, null);
INSERT INTO `categories` VALUES ('19', 'INTERNATIONAL', null, null, null);
INSERT INTO `categories` VALUES ('20', 'ISUZU', null, null, null);
INSERT INTO `categories` VALUES ('21', 'JEEP', null, null, null);
INSERT INTO `categories` VALUES ('22', 'JOHSON', null, null, null);
INSERT INTO `categories` VALUES ('23', 'JONHSON', null, null, null);
INSERT INTO `categories` VALUES ('24', 'KIA', null, null, null);
INSERT INTO `categories` VALUES ('25', 'L M V', null, null, null);
INSERT INTO `categories` VALUES ('26', 'LANCHA', null, null, null);
INSERT INTO `categories` VALUES ('27', 'LAND ROVER', null, null, null);
INSERT INTO `categories` VALUES ('28', 'LEXUS', null, null, null);
INSERT INTO `categories` VALUES ('29', 'MASEY FERGUSON', null, null, null);
INSERT INTO `categories` VALUES ('30', 'MAZDA', null, null, null);
INSERT INTO `categories` VALUES ('31', 'MERCEDES BENZ', null, null, null);
INSERT INTO `categories` VALUES ('32', 'MERCURY', null, null, null);
INSERT INTO `categories` VALUES ('33', 'MINI', null, null, null);
INSERT INTO `categories` VALUES ('34', 'MITSUBISHI', null, null, null);
INSERT INTO `categories` VALUES ('35', 'NISSAN', null, null, null);
INSERT INTO `categories` VALUES ('36', 'PEUGEOT', null, null, null);
INSERT INTO `categories` VALUES ('37', 'PONTIAC', null, null, null);
INSERT INTO `categories` VALUES ('38', 'RENAULT', null, null, null);
INSERT INTO `categories` VALUES ('39', 'REXTON', null, null, null);
INSERT INTO `categories` VALUES ('40', 'SALV', null, null, null);
INSERT INTO `categories` VALUES ('41', 'SCION', null, null, null);
INSERT INTO `categories` VALUES ('42', 'SEAT', null, null, null);
INSERT INTO `categories` VALUES ('43', 'SIMÁN', null, null, null);
INSERT INTO `categories` VALUES ('44', 'SMART', null, null, null);
INSERT INTO `categories` VALUES ('45', 'SSANGYONG', null, null, null);
INSERT INTO `categories` VALUES ('46', 'SUBARU', null, null, null);
INSERT INTO `categories` VALUES ('47', 'SUZUKI', null, null, null);
INSERT INTO `categories` VALUES ('48', 'TIGER', null, null, null);
INSERT INTO `categories` VALUES ('49', 'TOYOTA', null, null, null);
INSERT INTO `categories` VALUES ('50', 'TOYOTA ECHO', null, null, null);
INSERT INTO `categories` VALUES ('51', 'V W', null, null, null);
INSERT INTO `categories` VALUES ('52', 'VOLKSWAGEN', null, null, null);
INSERT INTO `categories` VALUES ('53', 'VOLSWAGEN', null, null, null);
INSERT INTO `categories` VALUES ('54', 'VOLVO', null, null, null);
INSERT INTO `categories` VALUES ('55', 'VW', null, null, null);
INSERT INTO `categories` VALUES ('56', 'YALE', null, null, null);
INSERT INTO `categories` VALUES ('57', 'YAMAHA', null, null, null);