INSERT INTO `subcategories` VALUES ('1', '1', 'QUATRO', null, null, null);
INSERT INTO `subcategories` VALUES ('2', '1', 'A4 QUATTRO', null, null, null);
INSERT INTO `subcategories` VALUES ('3', '2', '525 I', null, null, null);
INSERT INTO `subcategories` VALUES ('4', '2', '2002', null, null, null);
INSERT INTO `subcategories` VALUES ('5', '2', '320 I', null, null, null);
INSERT INTO `subcategories` VALUES ('6', '2', '535 I', null, null, null);
INSERT INTO `subcategories` VALUES ('7', '2', '325 I', null, null, null);
INSERT INTO `subcategories` VALUES ('8', '2', '528 I', null, null, null);
INSERT INTO `subcategories` VALUES ('9', '2', '328 I', null, null, null);
INSERT INTO `subcategories` VALUES ('10', '2', 'X5', null, null, null);
INSERT INTO `subcategories` VALUES ('11', '3', 'MONTECARLO', null, null, null);
INSERT INTO `subcategories` VALUES ('12', '3', 'S 10', null, null, null);
INSERT INTO `subcategories` VALUES ('13', '3', 'S-10', null, null, null);
INSERT INTO `subcategories` VALUES ('14', '3', 'PANEL C M V', null, null, null);
INSERT INTO `subcategories` VALUES ('15', '3', 'CELTA', null, null, null);
INSERT INTO `subcategories` VALUES ('16', '3', 'CMV', null, null, null);
INSERT INTO `subcategories` VALUES ('17', '3', 'METRO', null, null, null);
INSERT INTO `subcategories` VALUES ('18', '3', 'MONZA', null, null, null);
INSERT INTO `subcategories` VALUES ('19', '3', 'CORSA', null, null, null);
INSERT INTO `subcategories` VALUES ('20', '3', 'AVEO', null, null, null);
INSERT INTO `subcategories` VALUES ('21', '3', 'C M V', null, null, null);
INSERT INTO `subcategories` VALUES ('22', '3', 'BLAZER', null, null, null);
INSERT INTO `subcategories` VALUES ('23', '3', 'MALIBU', null, null, null);
INSERT INTO `subcategories` VALUES ('24', '3', 'CHEVY', null, null, null);
INSERT INTO `subcategories` VALUES ('25', '3', 'SPECTRUM', null, null, null);
INSERT INTO `subcategories` VALUES ('26', '3', 'C M P', null, null, null);
INSERT INTO `subcategories` VALUES ('27', '3', 'AVEO LS', null, null, null);
INSERT INTO `subcategories` VALUES ('28', '3', 'COLORADO', null, null, null);
INSERT INTO `subcategories` VALUES ('29', '4', 'P T CRUISER', null, null, null);
INSERT INTO `subcategories` VALUES ('30', '4', 'VOYAGER', null, null, null);
INSERT INTO `subcategories` VALUES ('31', '6', 'ATTIVO COACH', null, null, null);
INSERT INTO `subcategories` VALUES ('32', '6', 'ATIVO', null, null, null);
INSERT INTO `subcategories` VALUES ('33', '6', 'RACER GSI', null, null, null);
INSERT INTO `subcategories` VALUES ('34', '6', 'LABO', null, null, null);
INSERT INTO `subcategories` VALUES ('35', '6', 'FINO', null, null, null);
INSERT INTO `subcategories` VALUES ('36', '6', 'ATTIVO', null, null, null);
INSERT INTO `subcategories` VALUES ('37', '6', 'MATIZ', null, null, null);
INSERT INTO `subcategories` VALUES ('38', '6', 'MATIZ S', null, null, null);
INSERT INTO `subcategories` VALUES ('39', '7', 'CUORE', null, null, null);
INSERT INTO `subcategories` VALUES ('40', '7', 'CHARADE', null, null, null);
INSERT INTO `subcategories` VALUES ('41', '7', 'GRAN MOVE SE', null, null, null);
INSERT INTO `subcategories` VALUES ('42', '8', '120 Y', null, null, null);
INSERT INTO `subcategories` VALUES ('43', '9', 'RAM 1500', null, null, null);
INSERT INTO `subcategories` VALUES ('44', '9', 'NEON SXT', null, null, null);
INSERT INTO `subcategories` VALUES ('45', '9', 'CARAVAN', null, null, null);
INSERT INTO `subcategories` VALUES ('46', '9', 'CALIBER LXT', null, null, null);
INSERT INTO `subcategories` VALUES ('47', '9', 'RAM', null, null, null);
INSERT INTO `subcategories` VALUES ('48', '10', '40 HP', null, null, null);
INSERT INTO `subcategories` VALUES ('49', '10', 'INTRUDER', null, null, null);
INSERT INTO `subcategories` VALUES ('50', '11', '25', null, null, null);
INSERT INTO `subcategories` VALUES ('51', '12', 'ESCAPE', null, null, null);
INSERT INTO `subcategories` VALUES ('52', '12', 'FOCUS  ZX5', null, null, null);
INSERT INTO `subcategories` VALUES ('53', '12', 'ESCAPE XLS', null, null, null);
INSERT INTO `subcategories` VALUES ('54', '12', 'FOCUS', null, null, null);
INSERT INTO `subcategories` VALUES ('55', '12', 'RANGER', null, null, null);
INSERT INTO `subcategories` VALUES ('56', '12', 'EVEREST', null, null, null);
INSERT INTO `subcategories` VALUES ('57', '12', 'RANGER X L', null, null, null);
INSERT INTO `subcategories` VALUES ('58', '12', 'FOCUS  ZX 5', null, null, null);
INSERT INTO `subcategories` VALUES ('59', '12', 'RANGER LIMITED', null, null, null);
INSERT INTO `subcategories` VALUES ('60', '12', 'FOCUS ZX4', null, null, null);
INSERT INTO `subcategories` VALUES ('61', '12', 'RANGER X L T', null, null, null);
INSERT INTO `subcategories` VALUES ('62', '12', 'EXPLORER SPORT', null, null, null);
INSERT INTO `subcategories` VALUES ('63', '12', 'RANGER XLT', null, null, null);
INSERT INTO `subcategories` VALUES ('64', '12', 'FOCUS L X', null, null, null);
INSERT INTO `subcategories` VALUES ('65', '12', 'EXPLORER XLT', null, null, null);
INSERT INTO `subcategories` VALUES ('66', '12', 'RANGER  XL', null, null, null);
INSERT INTO `subcategories` VALUES ('67', '12', 'RANGER 4X4', null, null, null);
INSERT INTO `subcategories` VALUES ('68', '12', 'RANGER XL', null, null, null);
INSERT INTO `subcategories` VALUES ('69', '12', 'EVEREST XLT', null, null, null);
INSERT INTO `subcategories` VALUES ('70', '12', 'ESCORT SE', null, null, null);
INSERT INTO `subcategories` VALUES ('71', '12', 'MUSTANG', null, null, null);
INSERT INTO `subcategories` VALUES ('72', '12', 'EXPLORER', null, null, null);
INSERT INTO `subcategories` VALUES ('73', '12', 'ECOSPORT AMBI', null, null, null);
INSERT INTO `subcategories` VALUES ('74', '12', 'ECOSPORT XLS', null, null, null);
INSERT INTO `subcategories` VALUES ('75', '12', 'ESCAPE XLT', null, null, null);
INSERT INTO `subcategories` VALUES ('76', '12', 'EXPLORER SPOR', null, null, null);
INSERT INTO `subcategories` VALUES ('77', '13', 'CABEZAL', null, null, null);
INSERT INTO `subcategories` VALUES ('78', '14', 'METRO', null, null, null);
INSERT INTO `subcategories` VALUES ('79', '14', 'PRIZM', null, null, null);
INSERT INTO `subcategories` VALUES ('80', '14', 'TRACKER', null, null, null);
INSERT INTO `subcategories` VALUES ('81', '14', 'TRACKER SPORT', null, null, null);
INSERT INTO `subcategories` VALUES ('82', '15', 'C156', null, null, null);
INSERT INTO `subcategories` VALUES ('83', '17', 'CIVIC', null, null, null);
INSERT INTO `subcategories` VALUES ('84', '17', 'CR V 4X2', null, null, null);
INSERT INTO `subcategories` VALUES ('85', '17', 'CIVIC E X', null, null, null);
INSERT INTO `subcategories` VALUES ('86', '17', 'CRV LX', null, null, null);
INSERT INTO `subcategories` VALUES ('87', '17', 'ELEMENT', null, null, null);
INSERT INTO `subcategories` VALUES ('88', '17', 'CIVIC L X', null, null, null);
INSERT INTO `subcategories` VALUES ('89', '17', 'C R V', null, null, null);
INSERT INTO `subcategories` VALUES ('90', '17', 'CRV', null, null, null);
INSERT INTO `subcategories` VALUES ('91', '17', 'CIVIC LX', null, null, null);
INSERT INTO `subcategories` VALUES ('92', '17', 'ACCORD', null, null, null);
INSERT INTO `subcategories` VALUES ('93', '17', 'CRV  4WD', null, null, null);
INSERT INTO `subcategories` VALUES ('94', '17', 'CIVIC EX', null, null, null);
INSERT INTO `subcategories` VALUES ('95', '17', 'FIT', null, null, null);
INSERT INTO `subcategories` VALUES ('96', '17', 'CIVIC SI', null, null, null);
INSERT INTO `subcategories` VALUES ('97', '17', 'PILOT', null, null, null);
INSERT INTO `subcategories` VALUES ('98', '18', 'ELANTRA', null, null, null);
INSERT INTO `subcategories` VALUES ('99', '18', 'PANEL', null, null, null);
INSERT INTO `subcategories` VALUES ('100', '18', 'H-1', null, null, null);
INSERT INTO `subcategories` VALUES ('101', '18', 'GETZ GL', null, null, null);
INSERT INTO `subcategories` VALUES ('102', '18', 'ELANTRA GLS', null, null, null);
INSERT INTO `subcategories` VALUES ('103', '18', 'TIBURÓN', null, null, null);
INSERT INTO `subcategories` VALUES ('104', '18', 'ACCENT G L', null, null, null);
INSERT INTO `subcategories` VALUES ('105', '18', 'TIBURON', null, null, null);
INSERT INTO `subcategories` VALUES ('106', '18', 'ACCENT', null, null, null);
INSERT INTO `subcategories` VALUES ('107', '18', 'TUCSON', null, null, null);
INSERT INTO `subcategories` VALUES ('108', '18', 'H100', null, null, null);
INSERT INTO `subcategories` VALUES ('109', '18', 'H 1', null, null, null);
INSERT INTO `subcategories` VALUES ('110', '18', 'MATRIX GL', null, null, null);
INSERT INTO `subcategories` VALUES ('111', '18', 'H-100', null, null, null);
INSERT INTO `subcategories` VALUES ('112', '19', 'SCHOOL BUS', null, null, null);
INSERT INTO `subcategories` VALUES ('113', '20', 'RODEO', null, null, null);
INSERT INTO `subcategories` VALUES ('114', '20', 'PUP', null, null, null);
INSERT INTO `subcategories` VALUES ('115', '20', 'D MAX', null, null, null);
INSERT INTO `subcategories` VALUES ('116', '20', 'TFR', null, null, null);
INSERT INTO `subcategories` VALUES ('117', '20', 'PICK UP', null, null, null);
INSERT INTO `subcategories` VALUES ('118', '20', 'FSR33L-02', null, null, null);
INSERT INTO `subcategories` VALUES ('119', '20', 'NMR', null, null, null);
INSERT INTO `subcategories` VALUES ('120', '20', '4X4', null, null, null);
INSERT INTO `subcategories` VALUES ('121', '20', 'NPR', null, null, null);
INSERT INTO `subcategories` VALUES ('122', '20', 'NQR', null, null, null);
INSERT INTO `subcategories` VALUES ('123', '21', 'CHEROKEE', null, null, null);
INSERT INTO `subcategories` VALUES ('124', '21', 'CHEROKEE SPORT', null, null, null);
INSERT INTO `subcategories` VALUES ('125', '21', 'LIBERTY LTD', null, null, null);
INSERT INTO `subcategories` VALUES ('126', '21', 'GRAND CHEROKEE', null, null, null);
INSERT INTO `subcategories` VALUES ('127', '21', 'PATRIOT', null, null, null);
INSERT INTO `subcategories` VALUES ('128', '21', 'GRAND CHEROOKE', null, null, null);
INSERT INTO `subcategories` VALUES ('129', '21', 'LIBERTY', null, null, null);
INSERT INTO `subcategories` VALUES ('130', '21', 'WRANGLER', null, null, null);
INSERT INTO `subcategories` VALUES ('131', '21', 'COMPASS', null, null, null);
INSERT INTO `subcategories` VALUES ('132', '22', '6 H P', null, null, null);
INSERT INTO `subcategories` VALUES ('133', '23', '3.3 HP', null, null, null);
INSERT INTO `subcategories` VALUES ('134', '24', 'K 2700', null, null, null);
INSERT INTO `subcategories` VALUES ('135', '24', 'RIO R S', null, null, null);
INSERT INTO `subcategories` VALUES ('136', '24', 'SPORTAGE  EX', null, null, null);
INSERT INTO `subcategories` VALUES ('137', '24', 'CARENS', null, null, null);
INSERT INTO `subcategories` VALUES ('138', '24', 'OPTIMA L X', null, null, null);
INSERT INTO `subcategories` VALUES ('139', '24', 'TOWNER', null, null, null);
INSERT INTO `subcategories` VALUES ('140', '24', 'SEDONA E X', null, null, null);
INSERT INTO `subcategories` VALUES ('141', '24', 'CARNIVAL GS', null, null, null);
INSERT INTO `subcategories` VALUES ('142', '24', 'OPTIMA', null, null, null);
INSERT INTO `subcategories` VALUES ('143', '24', 'RIO', null, null, null);
INSERT INTO `subcategories` VALUES ('144', '24', 'SPORTAGE', null, null, null);
INSERT INTO `subcategories` VALUES ('145', '24', 'RIO E X', null, null, null);
INSERT INTO `subcategories` VALUES ('146', '24', 'SEPHIA', null, null, null);
INSERT INTO `subcategories` VALUES ('147', '24', 'SPECTRA EX', null, null, null);
INSERT INTO `subcategories` VALUES ('148', '24', 'K2700', null, null, null);
INSERT INTO `subcategories` VALUES ('149', '24', 'SPECTRA', null, null, null);
INSERT INTO `subcategories` VALUES ('150', '24', 'SPORTAGE LX', null, null, null);
INSERT INTO `subcategories` VALUES ('151', '24', 'SORENTO LX', null, null, null);
INSERT INTO `subcategories` VALUES ('152', '24', 'RIO LX', null, null, null);
INSERT INTO `subcategories` VALUES ('153', '24', 'ESPECTRA', null, null, null);
INSERT INTO `subcategories` VALUES ('154', '24', 'FORTE', null, null, null);
INSERT INTO `subcategories` VALUES ('155', '24', 'PICANTO', null, null, null);
INSERT INTO `subcategories` VALUES ('156', '24', 'RIO EX', null, null, null);
INSERT INTO `subcategories` VALUES ('157', '24', 'SPORTAGE EX', null, null, null);
INSERT INTO `subcategories` VALUES ('158', '24', 'SPORTGE LX', null, null, null);
INSERT INTO `subcategories` VALUES ('159', '24', 'K3600', null, null, null);
INSERT INTO `subcategories` VALUES ('160', '24', 'SOUL', null, null, null);
INSERT INTO `subcategories` VALUES ('161', '25', 'VESPA', null, null, null);
INSERT INTO `subcategories` VALUES ('162', '26', 'DEPORTIVO', null, null, null);
INSERT INTO `subcategories` VALUES ('163', '27', 'LR2 SE', null, null, null);
INSERT INTO `subcategories` VALUES ('164', '27', 'RANGE ROVER', null, null, null);
INSERT INTO `subcategories` VALUES ('165', '27', 'RANGE ROVER SPORT', null, null, null);
INSERT INTO `subcategories` VALUES ('166', '28', 'RX 300', null, null, null);
INSERT INTO `subcategories` VALUES ('167', '28', 'IS 250', null, null, null);
INSERT INTO `subcategories` VALUES ('168', '28', 'GX 470', null, null, null);
INSERT INTO `subcategories` VALUES ('169', '30', 'BT-50 HI', null, null, null);
INSERT INTO `subcategories` VALUES ('170', '30', 'E2200', null, null, null);
INSERT INTO `subcategories` VALUES ('171', '30', 'PROTEGE 5', null, null, null);
INSERT INTO `subcategories` VALUES ('172', '30', 'PROTEGE', null, null, null);
INSERT INTO `subcategories` VALUES ('173', '30', 'TRIBUTE', null, null, null);
INSERT INTO `subcategories` VALUES ('174', '30', '6 R', null, null, null);
INSERT INTO `subcategories` VALUES ('175', '30', '626', null, null, null);
INSERT INTO `subcategories` VALUES ('176', '30', '323', null, null, null);
INSERT INTO `subcategories` VALUES ('177', '30', '3', null, null, null);
INSERT INTO `subcategories` VALUES ('178', '30', '323 LX', null, null, null);
INSERT INTO `subcategories` VALUES ('179', '30', 'PROTEGE  L X', null, null, null);
INSERT INTO `subcategories` VALUES ('180', '30', 'B 2900', null, null, null);
INSERT INTO `subcategories` VALUES ('181', '30', '6', null, null, null);
INSERT INTO `subcategories` VALUES ('182', '30', '323 L X', null, null, null);
INSERT INTO `subcategories` VALUES ('183', '30', 'BT 50', null, null, null);
INSERT INTO `subcategories` VALUES ('184', '30', 'B2500', null, null, null);
INSERT INTO `subcategories` VALUES ('185', '30', '3 V', null, null, null);
INSERT INTO `subcategories` VALUES ('186', '30', 'B 2300', null, null, null);
INSERT INTO `subcategories` VALUES ('187', '30', '3000', null, null, null);
INSERT INTO `subcategories` VALUES ('188', '30', '626 GLX', null, null, null);
INSERT INTO `subcategories` VALUES ('189', '30', '6', null, null, null);
INSERT INTO `subcategories` VALUES ('190', '30', 'CX 7', null, null, null);
INSERT INTO `subcategories` VALUES ('191', '30', '6 V', null, null, null);
INSERT INTO `subcategories` VALUES ('192', '30', 'B2300', null, null, null);
INSERT INTO `subcategories` VALUES ('193', '30', '3V', null, null, null);
INSERT INTO `subcategories` VALUES ('194', '30', 'PROTEGE ES', null, null, null);
INSERT INTO `subcategories` VALUES ('195', '30', '323 GLX', null, null, null);
INSERT INTO `subcategories` VALUES ('196', '30', '3 SHREWSBURY', null, null, null);
INSERT INTO `subcategories` VALUES ('197', '31', '300', null, null, null);
INSERT INTO `subcategories` VALUES ('198', '31', 'E 240', null, null, null);
INSERT INTO `subcategories` VALUES ('199', '31', 'ML 320', null, null, null);
INSERT INTO `subcategories` VALUES ('200', '31', '250', null, null, null);
INSERT INTO `subcategories` VALUES ('201', '32', 'MARINO', null, null, null);
INSERT INTO `subcategories` VALUES ('202', '33', 'COOPER S', null, null, null);
INSERT INTO `subcategories` VALUES ('203', '34', 'L-200', null, null, null);
INSERT INTO `subcategories` VALUES ('204', '34', 'OUTLANDER', null, null, null);
INSERT INTO `subcategories` VALUES ('205', '34', 'MIRAGE', null, null, null);
INSERT INTO `subcategories` VALUES ('206', '34', 'LANCER G L', null, null, null);
INSERT INTO `subcategories` VALUES ('207', '34', 'MONTERO  I O', null, null, null);
INSERT INTO `subcategories` VALUES ('208', '34', 'L 300', null, null, null);
INSERT INTO `subcategories` VALUES ('209', '34', 'L 200', null, null, null);
INSERT INTO `subcategories` VALUES ('210', '34', 'NATIVA', null, null, null);
INSERT INTO `subcategories` VALUES ('211', '34', 'ECLIPSE', null, null, null);
INSERT INTO `subcategories` VALUES ('212', '34', 'LANCER', null, null, null);
INSERT INTO `subcategories` VALUES ('213', '34', 'LANCER GL', null, null, null);
INSERT INTO `subcategories` VALUES ('214', '34', 'LANCER ES', null, null, null);
INSERT INTO `subcategories` VALUES ('215', '34', 'LANCER GLX', null, null, null);
INSERT INTO `subcategories` VALUES ('216', '34', 'CANTER', null, null, null);
INSERT INTO `subcategories` VALUES ('217', '34', 'L300', null, null, null);
INSERT INTO `subcategories` VALUES ('218', '34', 'GALANT', null, null, null);
INSERT INTO `subcategories` VALUES ('219', '34', 'L200', null, null, null);
INSERT INTO `subcategories` VALUES ('220', '34', 'MONTERO', null, null, null);
INSERT INTO `subcategories` VALUES ('221', '34', 'PICK UP L 200', null, null, null);
INSERT INTO `subcategories` VALUES ('222', '34', 'LANCER EX', null, null, null);
INSERT INTO `subcategories` VALUES ('223', '34', 'OUTLANDER  ASX', null, null, null);
INSERT INTO `subcategories` VALUES ('224', '34', 'MONTERO GLS', null, null, null);
INSERT INTO `subcategories` VALUES ('225', '34', 'MONTERO IO', null, null, null);
INSERT INTO `subcategories` VALUES ('226', '34', 'MONTERO GL X', null, null, null);
INSERT INTO `subcategories` VALUES ('227', '34', 'ASX', null, null, null);
INSERT INTO `subcategories` VALUES ('228', '35', 'NAVARA SE', null, null, null);
INSERT INTO `subcategories` VALUES ('229', '35', 'FRONTIER', null, null, null);
INSERT INTO `subcategories` VALUES ('230', '35', 'SENTRA', null, null, null);
INSERT INTO `subcategories` VALUES ('231', '35', 'PATHFINDER', null, null, null);
INSERT INTO `subcategories` VALUES ('232', '35', 'Z24', null, null, null);
INSERT INTO `subcategories` VALUES ('233', '35', 'PICK UP', null, null, null);
INSERT INTO `subcategories` VALUES ('234', '35', 'SUNNY', null, null, null);
INSERT INTO `subcategories` VALUES ('235', '35', 'PLATINA', null, null, null);
INSERT INTO `subcategories` VALUES ('236', '35', 'ALMERA', null, null, null);
INSERT INTO `subcategories` VALUES ('237', '35', 'SENTRA 1.8', null, null, null);
INSERT INTO `subcategories` VALUES ('238', '35', 'SENTRA  GXE', null, null, null);
INSERT INTO `subcategories` VALUES ('239', '35', 'NAVARA', null, null, null);
INSERT INTO `subcategories` VALUES ('240', '35', 'PATROL', null, null, null);
INSERT INTO `subcategories` VALUES ('241', '35', 'ALTIMA', null, null, null);
INSERT INTO `subcategories` VALUES ('242', '35', 'PATROL S G L', null, null, null);
INSERT INTO `subcategories` VALUES ('243', '35', 'PICK UP D 21', null, null, null);
INSERT INTO `subcategories` VALUES ('244', '35', 'TIIDA  SE', null, null, null);
INSERT INTO `subcategories` VALUES ('245', '35', 'FRONTIER LCV', null, null, null);
INSERT INTO `subcategories` VALUES ('246', '35', 'D 21', null, null, null);
INSERT INTO `subcategories` VALUES ('247', '35', 'MURANO', null, null, null);
INSERT INTO `subcategories` VALUES ('248', '35', 'D21', null, null, null);
INSERT INTO `subcategories` VALUES ('249', '35', 'SENTRA S', null, null, null);
INSERT INTO `subcategories` VALUES ('250', '35', '200 SX', null, null, null);
INSERT INTO `subcategories` VALUES ('251', '35', 'SENTRA SR', null, null, null);
INSERT INTO `subcategories` VALUES ('252', '35', 'SENTRA GXE', null, null, null);
INSERT INTO `subcategories` VALUES ('253', '35', '4X4', null, null, null);
INSERT INTO `subcategories` VALUES ('254', '35', 'MARCH', null, null, null);
INSERT INTO `subcategories` VALUES ('255', '35', 'VERSA SL', null, null, null);
INSERT INTO `subcategories` VALUES ('256', '35', 'X TRAIL SE', null, null, null);
INSERT INTO `subcategories` VALUES ('257', '35', 'NAVARA LE', null, null, null);
INSERT INTO `subcategories` VALUES ('258', '35', 'TIIDA', null, null, null);
INSERT INTO `subcategories` VALUES ('259', '35', 'ROGUE', null, null, null);
INSERT INTO `subcategories` VALUES ('260', '35', 'VANETTE', null, null, null);
INSERT INTO `subcategories` VALUES ('261', '35', 'FRONTIER AX', null, null, null);
INSERT INTO `subcategories` VALUES ('262', '35', 'AD', null, null, null);
INSERT INTO `subcategories` VALUES ('263', '35', 'N/D', null, null, null);
INSERT INTO `subcategories` VALUES ('264', '35', 'VERSA', null, null, null);
INSERT INTO `subcategories` VALUES ('265', '35', 'JUKE', null, null, null);
INSERT INTO `subcategories` VALUES ('266', '36', 'PARTNER', null, null, null);
INSERT INTO `subcategories` VALUES ('267', '36', '206 X R', null, null, null);
INSERT INTO `subcategories` VALUES ('268', '36', '206 XR', null, null, null);
INSERT INTO `subcategories` VALUES ('269', '36', '206', null, null, null);
INSERT INTO `subcategories` VALUES ('270', '36', '206 XRPR  HDI', null, null, null);
INSERT INTO `subcategories` VALUES ('271', '36', '307 XR', null, null, null);
INSERT INTO `subcategories` VALUES ('272', '36', '207 SPORT 1.6', null, null, null);
INSERT INTO `subcategories` VALUES ('273', '36', '405', null, null, null);
INSERT INTO `subcategories` VALUES ('274', '36', '406 ST', null, null, null);
INSERT INTO `subcategories` VALUES ('275', '37', 'VIBE', null, null, null);
INSERT INTO `subcategories` VALUES ('276', '38', 'SCENIC', null, null, null);
INSERT INTO `subcategories` VALUES ('277', '38', 'CLIO', null, null, null);
INSERT INTO `subcategories` VALUES ('278', '41', 'TC', null, null, null);
INSERT INTO `subcategories` VALUES ('279', '41', 'XB', null, null, null);
INSERT INTO `subcategories` VALUES ('280', '42', 'CORDOBA', null, null, null);
INSERT INTO `subcategories` VALUES ('281', '44', 'FORTWO', null, null, null);
INSERT INTO `subcategories` VALUES ('282', '45', 'KYRON M200', null, null, null);
INSERT INTO `subcategories` VALUES ('283', '45', 'REXTON RX290', null, null, null);
INSERT INTO `subcategories` VALUES ('284', '46', 'LEGACY', null, null, null);
INSERT INTO `subcategories` VALUES ('285', '47', 'JIMMY', null, null, null);
INSERT INTO `subcategories` VALUES ('286', '47', 'STEEM', null, null, null);
INSERT INTO `subcategories` VALUES ('287', '47', 'GRAND VITARA', null, null, null);
INSERT INTO `subcategories` VALUES ('288', '47', 'FORENZA', null, null, null);
INSERT INTO `subcategories` VALUES ('289', '47', 'A X 100', null, null, null);
INSERT INTO `subcategories` VALUES ('291', '47', ' AX 100', null, null, null);
INSERT INTO `subcategories` VALUES ('292', '47', 'ESTEEM', null, null, null);
INSERT INTO `subcategories` VALUES ('293', '47', 'AEREO SX', null, null, null);
INSERT INTO `subcategories` VALUES ('294', '47', 'SAMURAI', null, null, null);
INSERT INTO `subcategories` VALUES ('295', '47', 'APV', null, null, null);
INSERT INTO `subcategories` VALUES ('296', '47', 'XL 7', null, null, null);
INSERT INTO `subcategories` VALUES ('297', '47', 'GN 125 F', null, null, null);
INSERT INTO `subcategories` VALUES ('298', '47', 'SX 4', null, null, null);
INSERT INTO `subcategories` VALUES ('299', '47', 'GN 125 H', null, null, null);
INSERT INTO `subcategories` VALUES ('300', '47', 'GN 125H', null, null, null);
INSERT INTO `subcategories` VALUES ('301', '48', 'SPORT', null, null, null);
INSERT INTO `subcategories` VALUES ('302', '49', 'COROLLA', null, null, null);
INSERT INTO `subcategories` VALUES ('303', '49', 'TERCEL', null, null, null);
INSERT INTO `subcategories` VALUES ('304', '49', 'ECHO', null, null, null);
INSERT INTO `subcategories` VALUES ('305', '49', 'YARIS', null, null, null);
INSERT INTO `subcategories` VALUES ('306', '49', 'STARLET', null, null, null);
INSERT INTO `subcategories` VALUES ('307', '49', 'COROLLA TERCEL', null, null, null);
INSERT INTO `subcategories` VALUES ('308', '49', 'HI ACE', null, null, null);
INSERT INTO `subcategories` VALUES ('309', '49', 'CORONA', null, null, null);
INSERT INTO `subcategories` VALUES ('310', '49', 'COROLLA CE', null, null, null);
INSERT INTO `subcategories` VALUES ('311', '49', 'COROLLA SE', null, null, null);
INSERT INTO `subcategories` VALUES ('312', '49', 'RAV 4X4', null, null, null);
INSERT INTO `subcategories` VALUES ('313', '49', 'HILUX', null, null, null);
INSERT INTO `subcategories` VALUES ('314', '49', 'CORONA GL', null, null, null);
INSERT INTO `subcategories` VALUES ('315', '49', 'COROLLA XLI', null, null, null);
INSERT INTO `subcategories` VALUES ('316', '49', 'LAND CRUISER', null, null, null);
INSERT INTO `subcategories` VALUES ('317', '49', 'MATRIX', null, null, null);
INSERT INTO `subcategories` VALUES ('318', '49', 'COROLLA GLI', null, null, null);
INSERT INTO `subcategories` VALUES ('319', '49', 'LITEACE', null, null, null);
INSERT INTO `subcategories` VALUES ('320', '49', 'HI LUX', null, null, null);
INSERT INTO `subcategories` VALUES ('321', '49', 'FOUR RUNNER SR5', null, null, null);
INSERT INTO `subcategories` VALUES ('322', '49', 'TACOMA', null, null, null);
INSERT INTO `subcategories` VALUES ('323', '49', 'FOUR RUNNER', null, null, null);
INSERT INTO `subcategories` VALUES ('324', '49', 'RAV 4', null, null, null);
INSERT INTO `subcategories` VALUES ('325', '49', 'RAV 4 XLE', null, null, null);
INSERT INTO `subcategories` VALUES ('326', '49', 'FORTUNER', null, null, null);
INSERT INTO `subcategories` VALUES ('327', '49', 'LAND CRUSIER PRADO', null, null, null);
INSERT INTO `subcategories` VALUES ('328', '49', 'DYNA', null, null, null);
INSERT INTO `subcategories` VALUES ('329', '49', 'SCION', null, null, null);
INSERT INTO `subcategories` VALUES ('330', '49', 'SCION XB', null, null, null);
INSERT INTO `subcategories` VALUES ('331', '52', 'FOX 1.6', null, null, null);
INSERT INTO `subcategories` VALUES ('332', '52', 'SAVEIRO', null, null, null);
INSERT INTO `subcategories` VALUES ('333', '52', 'POLO COMFORT L', null, null, null);
INSERT INTO `subcategories` VALUES ('334', '52', 'GOLF', null, null, null);
INSERT INTO `subcategories` VALUES ('335', '52', 'JETTA EUROPA', null, null, null);
INSERT INTO `subcategories` VALUES ('336', '52', '113-1500', null, null, null);
INSERT INTO `subcategories` VALUES ('337', '52', 'TIGUAN', null, null, null);
INSERT INTO `subcategories` VALUES ('338', '52', 'KEFER', null, null, null);
INSERT INTO `subcategories` VALUES ('339', '52', 'PARATI', null, null, null);
INSERT INTO `subcategories` VALUES ('340', '52', 'GOL', null, null, null);
INSERT INTO `subcategories` VALUES ('341', '52', 'BEETLE', null, null, null);
INSERT INTO `subcategories` VALUES ('342', '52', 'COMBI', null, null, null);
INSERT INTO `subcategories` VALUES ('343', '52', 'JETTA', null, null, null);
INSERT INTO `subcategories` VALUES ('344', '52', 'ESCARABAJO', null, null, null);
INSERT INTO `subcategories` VALUES ('345', '52', 'JETTA GL 2.0', null, null, null);
INSERT INTO `subcategories` VALUES ('346', '52', 'GOLF VARIANT', null, null, null);
INSERT INTO `subcategories` VALUES ('347', '54', '245', null, null, null);
INSERT INTO `subcategories` VALUES ('348', '54', 'S 60', null, null, null);
INSERT INTO `subcategories` VALUES ('349', '54', 'S 70', null, null, null);
INSERT INTO `subcategories` VALUES ('350', '54', 'C 30  T5', null, null, null);
INSERT INTO `subcategories` VALUES ('351', '56', 'GTP30TK', null, null, null);
INSERT INTO `subcategories` VALUES ('352', '57', 'YD 110 S', null, null, null);
INSERT INTO `subcategories` VALUES ('353', '57', '750 SS', null, null, null);
INSERT INTO `subcategories` VALUES ('354', '57', 'YFM 350 FWA', null, null, null);
INSERT INTO `subcategories` VALUES ('355', '57', '250 HP', null, null, null);
INSERT INTO `subcategories` VALUES ('356', '57', 'YBR 125', null, null, null);
INSERT INTO `subcategories` VALUES ('357', '57', 'OUTBOARD', null, null, null);
INSERT INTO `subcategories` VALUES ('358', '3', 'AVEEO 5 LT', null, null, null);
INSERT INTO `subcategories` VALUES ('359', '55', 'Jetta', null, '2020-04-07 09:50:08', '2020-04-07 09:50:08');